/**
 * Let somebody into a hackathon from the terminal.
 *
 * The organizer console does this in the product and is the right place for it.
 * This exists for the case the console cannot cover: an event whose organizer
 * key was generated by a script rather than held in a wallet, which is every
 * test hackathon on testnet. Without it those events can be applied to and
 * never entered.
 *
 * It applies on the applicant's behalf only if they have not already, and only
 * with their own secret. An approval with no application behind it is a state
 * the contract refuses, and it should: being let in is an answer to somebody
 * asking.
 *
 *   node --experimental-strip-types scripts/approve.mts <core> <organizer secret> <address>
 */

import {
  Address,
  BASE_FEE,
  Contract,
  Keypair,
  TransactionBuilder,
  scValToNative,
  xdr,
} from "@stellar/stellar-sdk/base";
import { Api, Server, assembleTransaction } from "@stellar/stellar-sdk/rpc";

const RPC = "https://soroban-testnet.stellar.org";
const PASSPHRASE = "Test SDF Network ; September 2015";

const core = process.argv[2];
const organizerSecret = process.argv[3];
const address = process.argv[4];

if (core === undefined || organizerSecret === undefined || address === undefined) {
  throw new Error("usage: approve.mts <core> <organizer secret> <address>");
}

const server = new Server(RPC);
const organizer = Keypair.fromSecret(organizerSecret);

async function call(who: Keypair, method: string, ...args: xdr.ScVal[]): Promise<void> {
  const source = await server.getAccount(who.publicKey());
  const built = new TransactionBuilder(source, { fee: BASE_FEE, networkPassphrase: PASSPHRASE })
    .addOperation(new Contract(core!).call(method, ...args))
    .setTimeout(180)
    .build();

  const simulated = await server.simulateTransaction(built);

  if (Api.isSimulationError(simulated)) {
    throw new Error(`${method}: ${simulated.error.slice(0, 300)}`);
  }

  const prepared = assembleTransaction(built, simulated).build();
  prepared.sign(who);

  const sent = await server.sendTransaction(prepared);
  const done = await server.pollTransaction(sent.hash, { attempts: 40, sleepStrategy: () => 1000 });

  if (done.status !== "SUCCESS") {
    throw new Error(`${method}: ${done.status}`);
  }
}

/* Read first, so running this twice is not an error and so an address that
   never applied is reported as that rather than as a failed approval. */
const nobody = new (await import("@stellar/stellar-sdk/base")).Account(
  "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
  "0",
);

const asked = new TransactionBuilder(nobody, { fee: BASE_FEE, networkPassphrase: PASSPHRASE })
  .addOperation(new Contract(core).call("registration", new Address(address).toScVal()))
  .setTimeout(30)
  .build();

const answer = await server.simulateTransaction(asked);
const registration =
  Api.isSimulationError(answer) || answer.result === undefined
    ? null
    : (scValToNative(answer.result.retval) as { status?: unknown } | null);

const status = Number(registration?.status ?? -1);

console.log("standing :", registration === null ? "no application" : status);

if (registration === null || status < 0) {
  throw new Error(
    `${address} has not applied to this hackathon. They press "Register as a hacker" first.`,
  );
}

if (status === 1) {
  console.log("already in ✓");
} else {
  await call(
    organizer,
    "approve_application",
    new Address(organizer.publicKey()).toScVal(),
    new Address(address).toScVal(),
  );

  console.log("approved ✓", address);
}
